### PR TITLE
feat: Support rotating inserters with custom drop/pickup locations

### PR DESCRIPTION
**Pull request by Marwes**
I think this is correct? I tried to mirror the handling of loaders here. Seems to work from manual testing at least.

Part of https://github.com/GlassBricks/StagedBlueprintPlanning/issues/28

### CODE REVIEW

**Comment by Marwes** [comment]
Flipping seems to only be possible with blueprints and is still broken (the ghost will update but when placing the blueprint it is in the original configuration)

**Comment by GlassBricks** [comment]
Thanks for the PR!

However, I literally just now made on another different fix that seems to work with flipped blueprints as well (see the `patch` branch).

**Comment by Marwes** [comment]
Tried your fix and it only seems to apply for blueprints/ghosts, if you press 'R' to rotate on an entity placed in the world it is still bugged. So I think both this fix and yours are needed.

**Comment by Marwes** [comment]
Can't reopen this one so had to open a new one. I think that is the correct fix at least.

**Pull request closed without merging**
